LibraryManagement_FrontEnd/Controllers/LendBookUserController.cs
using LibraryManagement_FrontEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace LibraryManagement_FrontEnd.Controllers
{
    public class LendBookUserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly string apiLendBookRequestsUrl;
        private IConfiguration _Configure;

        public LendBookUserController(IConfiguration configuration,ApplicationDbContext db, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _Configure = configuration;
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
            apiLendBookRequestsUrl = _Configure.GetValue<string>("WebAPILendBookRequestsUrl");
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllLendRequestByUser()
        {
            List<LendBookRequests> request = new List<LendBookRequests>();
            using (var client = new HttpClient())
            {
                var user = await _userManager.GetUserAsync(User);
                client.BaseAddress = new Uri($"{apiLendBookRequestsUrl}/GetAllLendBookRequestsByUserName?username={user.UserName}");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync($"{apiLendBookRequestsUrl}/GetAllLendBookRequestsByUserName?username={user.UserName}");
                if (Res.IsSuccessStatusCode)
                {
                    var LendBookRequestsResponse = Res.Content.ReadAsStringAsync().Result;
                    request = JsonConvert.DeserializeObject<List<LendBookRequests>>(LendBookRequestsResponse);
                    return Ok(request);
                }
                return NotFound();
            }
        }

        public async Task<IActionResult> ViewBill()
        {
            List<LendBookRequests> request = new List<LendBookRequests>();
            using (var client = new HttpClient())
            {
                var user = await _userManager.GetUserAsync(User);
                client.BaseAddress = new Uri($"{apiLendBookRequestsUrl}/GetAllLendBookRequestsByUserName?username={user.UserName}");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync($"{apiLendBookRequestsUrl}/GetAllLendBookRequestsByUserName?username={user.UserName}");
                if (Res.IsSuccessStatusCode)
                {
                    var LendBookRequestsResponse = Res.Content.ReadAsStringAsync().Result;
                    request = JsonConvert.DeserializeObject<List<LendBookRequests>>(LendBookRequestsResponse);

                    request = request.Where(u => u.Status == "Accepted").ToList();
                    if (request.Count == 0)
                    {
                        TempData["error"] = "You have not borrowed any book or Your borrow request is Pending!";
                        return RedirectToAction("Index", "Home");
                    }
                    return View(request);
                }
                return NotFound();
            }
        }

        
        
        public IActionResult PaymentPage(int TotalAmount,int OrderId)
        {
            ViewBag.TotalAmount = TotalAmount;
            ViewBag.OrderId = OrderId;
            return View();
        } 
        public IActionResult ConfirmationPage(int TotalAmount,int OrderId)
        {
            ViewBag.paidAmount = TotalAmount;
            return View(OrderId);
        }

    }
}

LibraryManagement_FrontEnd/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagement_FrontEnd.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
  <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
      @if(signInManager.IsSignedIn(User)){
           @if (!Convert.ToBoolean(@User.FindFirst("IsAdmin").Value))
               {
            <li class="nav-item">
          <a class="nav-link text-dark" asp-controller="LendBookUser" asp-action="Index">Borrow Requests</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-controller="LendBookUser" asp-action="ViewBill">View Bill</a>
        </li>
              }
           }
        @if (signInManager.IsSignedIn(User)){
            @if(Convert.ToBoolean(@User.FindFirst("IsAdmin").Value)){
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Content Management
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="nav-link text-dark" asp-controller="Books" asp-action="Index">Books</a></li>
            <li><a class="nav-link text-dark" asp-controller="Authors" asp-action="Index">Authors</a></li>
            <li><a class="nav-link text-dark" asp-controller="Publishers" asp-action="Index">Publishers</a></li>
            <li><a class="nav-link text-dark" asp-controller="LendBook" asp-action="Index">Lend Requests</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="nav-link text-dark" asp-controller="Account" asp-action="Index">Users</a></li>
          </ul>
        </li>
        }
        }
        
      </ul>

      @if (!signInManager.IsSignedIn(User)){
    <a asp-controller="Account" asp-action="Login" class="btn btn-dark mx-2">Login</a>
    
    }
    else{
        <form method="post" asp-action="Logout">
        <button asp-controller="Account" asp-action="Logout" class="btn btn-dark mx-2">Logout</button>
        </form>
        <h5 class="mx-2">Hello @User.FindFirst("Name").Value!</h5>
    }
      @*<form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container">
            &copy; 2022 - LibraryManagement_FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryManagement_FrontEnd/Views/Shared/_Notification.cshtml
@if (TempData["title"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]','@TempData["title"]')
    </script>
    
}

@if (TempData["success"] != null && TempData["title"]==null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
    
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}